baseURL: "https://slangbrain.com/"
copyright: "Â© 2017 Jorin Vogel"
title: "Slangbrain"

outputs:
  home:
  - html
  - amp
  - rss
  - css
  page:
  - html
  - amp
  - json

enablerobotstxt: true

params:
  boturl: "https://m.me/slangbrain"
  langicons:
    german: ğŸ‡©ğŸ‡ª
    swedish: ğŸ‡¸ğŸ‡ª
    japanese: ğŸ‡¯ğŸ‡µ
    thai: ğŸ‡¹ğŸ‡­

Languages:
  en:
    weight: 1
  de:
    weight: 2
