baseURL: "https://slangbrain.com/"
copyright: "© 2017 Jorin Vogel"
title: "Slangbrain"

outputs:
  home:
  - html
  - amp
  - rss
  - css
  page:
  - html
  - amp
  - json

enablerobotstxt: true

params:
  boturl: "https://m.me/slangbrain"
  langs:
    en: 'English'
    de: 'Deutsch'
    fr: 'Français'
    jp: '日本語'
    se: 'Svenska'
    th: 'ภาษาไทย'

Languages:
  en:
    weight: 1
  de:
    weight: 2
