baseURL: "https://slangbrain.com/"
copyright: "Â© 2017 Jorin Vogel"
title: "Slangbrain"

outputs:
  home:
  - html
  - amp
  - rss
  - css
  page:
  - html
  - amp
  - json

enablerobotstxt: true

params:
  boturl: "https://m.me/slangbrain"
  langicons:
    gb: ğŸ‡¬ğŸ‡§
    de: ğŸ‡©ğŸ‡ª
    se: ğŸ‡¸ğŸ‡ª
    jp: ğŸ‡¯ğŸ‡µ
    th: ğŸ‡¹ğŸ‡­

Languages:
  en:
    weight: 1
  de:
    weight: 2
